### ISSUE TITLE
Pull quotes

### ISSUE THREAD

**Issue by bruskiza** [praekelt/molo#37]
Pull quotes ala https://b-wise.mobi/english/know-your-body/healthy-living/eat-not-good-food-rules-live/

<img width="819" alt="eat_this__not_that__good_food_rules_to_live_by" src="https://cloud.githubusercontent.com/assets/165585/9361786/7426617a-469d-11e5-9926-b69d906dcb1d.png">

should not have to be hacked with h4's in the markdown.

There should be a more elegant solution.

**Comment by smn** [comment]
This is a styling issue. Markdown allows one to create blockquotes using `> ` before the actual quote. Also I don't think this is a `molo.core` issue but rather a project specific implementation issue w/ styling?

**Comment by smn** [comment]
![wagtail_-_editing_article__eat_this__not_that__good_food_rules_to_live_by_and_eat_this__not_that__good_food_rules_to_live_by](https://cloud.githubusercontent.com/assets/1065/9362873/55a9936a-46a3-11e5-8815-44688fc79c9d.jpg)

Example using blockquotes:

```markdown
Drink water if you are thirsty - not a cold drinks, energy drinks or juice. Avoid junk food and take-aways. 

> Avoid hamburgers, fried chicken, chips, sweets, pies, pastries, doughnuts, white bread and ice creams.
```

**Comment by miltontony** [comment]
@smn thanks. I was planning to add it as one of those helper block-types.
