### ISSUE TITLE
Markdown editor toolbar

### ISSUE THREAD

**Issue by miltontony** [praekelt/molo#46]
We need to implement a toolbar for editing markdown.

See this example:
http://madebymany.github.io/sir-trevor-js/example.html

Some googling might help

git repo:
https://github.com/praekelt/molo

**Comment by nathanbegbie** [comment]
@miltontony : Trying to nail down exactly what functionality you want. Sir Trevor looks like a bit of an overkill if you just want to edit text, but is it the WYSIWYG style that you want?
